Repository eclipse-zenoh/zenoh-plugin-mqtt, pull requests merged in 2024-09, with the labels that each got.

#197 Fix the panic
  zenoh-plugin-mqtt/src/lib.rs
Labels: bug

#204 Update zenoh
  Cargo.lock
  zenoh-bridge-mqtt/src/main.rs
  zenoh-plugin-mqtt/src/lib.rs
  zenoh-plugin-mqtt/src/mqtt_session_state.rs
Labels: internal

#205 Update zenoh
  Cargo.lock
Labels: internal

#211 Align with Rust
  Cargo.lock
  Cargo.toml
  zenoh-bridge-mqtt/Cargo.toml
  zenoh-bridge-mqtt/src/main.rs
  zenoh-plugin-mqtt/Cargo.toml
  zenoh-plugin-mqtt/src/config.rs
  zenoh-plugin-mqtt/src/lib.rs
Labels: internal

#210 Update ntex-mqtt
  Cargo.lock
  Cargo.toml
  zenoh-bridge-mqtt/src/main.rs
  zenoh-plugin-mqtt/src/lib.rs
Labels: enhancement

#218 fix: using static_plugin feature of rest plugin
  Cargo.toml
Labels: internal

#224 Revert "Update ntex-mqtt (#210)"
  .github/workflows/ci.yml
  Cargo.lock
  Cargo.toml
  zenoh-bridge-mqtt/src/main.rs
  zenoh-plugin-mqtt/src/lib.rs
Labels: bug

#227 Bump ntex, ntex-mqtt, and other crate version.
  Cargo.lock
  Cargo.toml
  zenoh-bridge-mqtt/src/main.rs
  zenoh-plugin-mqtt/src/lib.rs
Labels: enhancement

#228 Disable the default-feature in rustls.
  Cargo.lock
  Cargo.toml
Labels: bug

#229 chore: update release.yml for required labels
  .github/release.yml
Labels: internal
