Repository eclipse-zenoh/zenoh-plugin-mqtt, pull requests merged in 2024-10, with the labels that each got.

#232 update to use new serialization
  Cargo.lock
  Cargo.toml
  zenoh-plugin-mqtt/src/lib.rs
  zenoh-plugin-mqtt/src/mqtt_session_state.rs
Labels: enhancement, dependencies, release, internal

#237 Updated Zenoh subscriber and queryable declarations to undeclare entities when references are dropped.
  zenoh-plugin-mqtt/src/lib.rs
  zenoh-plugin-mqtt/src/mqtt_session_state.rs
Labels: bug

#244 removed guess encoding
  Cargo.lock
  zenoh-plugin-mqtt/src/mqtt_helpers.rs
  zenoh-plugin-mqtt/src/mqtt_session_state.rs
Labels: release, internal
